version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
      day: monday
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
    groups:
      github-actions:
        patterns: ["*"]
