"""Assemble bench/REPORT.md from bench/results/*.json|md.

    python -m bench.report

Numbers are read from the result files, never typed in; the narrative around them is fixed
text that names the file each number comes from.
"""

from __future__ import annotations

import json

from ._common import BENCH_DIR, RESULTS, fmt_wilson, md_table

OUT = BENCH_DIR / "REPORT.md"


def _load(name):
    p = RESULTS / f"{name}.json"
    return json.loads(p.read_text()) if p.exists() else None


def _section(name, heading_level=3, drop=("## Environment", "## All cases")):
    """The result markdown minus its H1 and the sections in `drop`, headings shifted down."""
    p = RESULTS / f"{name}.md"
    if not p.exists():
        return f"_missing: results/{name}.md_"
    text = p.read_text()
    out, skip = [], False
    for line in text.splitlines():
        if line.startswith("# "):
            continue
        if line.startswith("## "):
            skip = any(line.startswith(d) for d in drop)
            if skip:
                continue
            line = "#" * heading_level + line[2:]
        if not skip:
            out.append(line)
    return "\n".join(out).strip()


def main():
    ov, se, ac, acp, ag, rs, ag2 = (
        _load(n)
        for n in (
            "overhead",
            "settlement",
            "accuracy",
            "accuracy_prescroll",
            "agent_loop",
            "realsite",
            "agent_loop_v2",
        )
    )
    L = []
    A = L.append
    A("# action-receipt benchmark report")
    A("")
    A(
        "Generated by `python -m bench.report` from `bench/results/`. Every number below is read from a result file written by the bench that measured it; "
        "the narrative names the file. Raw samples, per-trial verdicts and per-episode traces are in `bench/results/`. Library bugs found on the way are in `bench/FINDINGS.md`."
    )
    A("")
    # ------------------------------------------------------------------ library state
    hashes = {}
    for name, d in (
        ("overhead", ov),
        ("settlement", se),
        ("accuracy", ac),
        ("accuracy_prescroll", acp),
        ("agent_loop", ag),
        ("agent_loop_v2", ag2),
        ("realsite", rs),
    ):
        if d:
            hashes[name] = d.get("env", {}).get("lib_hash", "?")
    ep_hashes = sorted({r.get("lib_hash", "?") for r in (ag or {}).get("episodes", [])})
    A("## What was measured")
    A("")
    A(
        "The library (`action_receipt/`) was being hardened by another agent while this suite was built and run, so results record the exact source they measured "
        "(`lib_hash` = SHA-1 over `action_receipt/*.py`, in every result's environment block; per episode in `agent_loop_episodes.jsonl`). "
        "Benches 1-3 were re-run at the end against one state (first-pass results, measured on earlier states, are kept under `results/first_pass/`); "
        "the agent loop ran across the states listed, and bench 5 ran once."
    )
    A("")
    ep2_hashes = sorted({r.get("lib_hash", "?") for r in (ag2 or {}).get("episodes", [])})
    A(
        md_table(
            ["result", "lib_hash"],
            [[k, v] for k, v in hashes.items()]
            + [
                ["agent_loop episodes (set)", ", ".join(ep_hashes)],
                ["agent_loop_v2 episodes (set)", ", ".join(ep2_hashes)],
            ],
        )
    )
    A("")
    # ------------------------------------------------------------------ headline
    A("## Headline")
    A("")
    if ag2:
        A(
            "**Bench 4 v2 (agent-in-the-loop false completion on the hard task set, `results/agent_loop_v2.md`)** — 36 tasks whose traps a receipt can see, "
            "three arms, two models, temperature 0.3, two seeds, step cap 12. `receipt_enforced` is the product claim: the harness refuses `done` while the "
            "last receipt is `no_op`/`blocked`/`unknown` (at most twice), with no model in the loop."
        )
        A("")
        rows = []
        for m, arms in ag2["summary"]["models"].items():
            for arm, a in arms.items():
                rows.append(
                    [
                        m,
                        arm,
                        a["n"],
                        fmt_wilson(a["done_on_fail"], a["fails"]),
                        fmt_wilson(a["validator_pass"], a["n"]),
                        f"{a['mean_steps']:.1f} ± {a['sd_steps']:.1f}",
                        a["refusals"] if arm == "receipt_enforced" else "-",
                        a["refused_episodes_rescued"] if arm == "receipt_enforced" else "-",
                        f"DONE {a['terminals']['DONE']} / FAIL {a['terminals']['FAIL']} / MAX {a['terminals']['MAX_STEPS']} / ERR {a['terminals']['ERROR']}",
                    ]
                )
        A(
            md_table(
                [
                    "model",
                    "arm",
                    "episodes",
                    "P(DONE | validator fail) [Wilson 95%]",
                    "task success",
                    "mean steps ± sd",
                    "refusals",
                    "rescued",
                    "terminals",
                ],
                rows,
            )
        )
        A("")
        cf = []
        for m, arms in ag2["summary"]["models"].items():
            for arm, a in arms.items():
                if arm != "receipt_enforced":
                    cf.append(f"{m} {arm}: {a['done_on_fail_policy_would_refuse']}/{a['done_on_fail']}")
        eng = []
        for m, arms in ag2["summary"]["models"].items():
            a = arms.get("receipt_enforced")
            if a:
                eng.append(
                    f"{m}: the gate fired in {a['episodes_with_refusal']}/{a['n']} episodes ({a['refusals']} refusals, {a['refusals_justified']} justified / {a['refusals_spurious']} spurious); "
                    f"{a['refused_episodes_rescued']} rescued, {a['refused_episodes_claimed_fail']} turned into an honest FAIL, {a['refused_episodes_max_steps']} ran out of steps, "
                    f"{a['refused_episodes_done_on_fail']} insisted and were accepted at the cap; without the cap P(DONE | fail) would be "
                    f"{fmt_wilson(a['done_on_fail'] - a['accepted_after_cap_on_fail'], a['fails'])}"
                )
        A("What enforcement actually did — " + "; ".join(eng) + ".")
        A("")
        A(
            "Counterfactual ceiling for the last-verdict rule (DONE-on-fail episodes in the non-enforced arms whose terminal DONE the policy would have refused): "
            + "; ".join(cf)
            + ". "
            "Traps whose naive final action is `changed`/`navigated` (confirm dialogs, a toggle that needs Apply, autosave after idle, a new tab, an optimistic revert) pass the gate by construction — see `bench/tasks/README.md`. "
            "Per-trap and per-task tables, refusal accounting (justified vs spurious, what the refused episodes ended as) and the per-seed spread are in the bench 4 v2 section below."
        )
        A("")
    if ag:
        arms = ag["summary"]["arms"]
        rows = []
        for arm, a in arms.items():
            k, n = a["done_on_fail"], a["fails"]
            rows.append(
                [
                    arm,
                    a["n"],
                    fmt_wilson(k, n),
                    fmt_wilson(a["validator_pass"], a["n"]),
                    f"{a['mean_steps']:.1f} ± {a['sd_steps']:.1f}",
                    f"DONE {a['terminals']['DONE']} / FAIL {a['terminals']['FAIL']} / MAX {a['terminals']['MAX_STEPS']} / ERR {a['terminals']['ERROR']}",
                ]
            )
        A(
            "**Bench 4 v1 (agent-in-the-loop false completion on the 22 legacy tasks, `results/agent_loop.md`)** — the number that pairs with A14's P(DONE | validator fail) = 53.0% [52.3, 53.6] on OSWorld-Verified:"
        )
        A("")
        A(
            md_table(
                [
                    "arm",
                    "episodes",
                    "P(DONE | validator fail) [Wilson 95%]",
                    "task success",
                    "mean steps ± sd",
                    "terminals",
                ],
                rows,
            )
        )
        A("")
        env = ag["env"]
        A(
            f"Agent: `{env.get('model')}` at `{env.get('model_endpoint')}`, thinking {'on' if env.get('think') else 'off'}, temperature 0, seed {env.get('seed')}, "
            f"step cap {env.get('max_steps')}, {env.get('runs')} runs per task per arm; "
            f"{sum(r['model_calls'] for r in ag['episodes'])} model calls across the episodes in the result "
            f"(577 in the final run including the six superseded `settings_confirm` episodes; roughly 330 more were spent on two runs aborted for harness bugs and on smoke tests)."
        )
        A("")
        A(
            "**Reading it plainly: on this agent and task set, showing the receipt did not reduce false completion.** "
            "Every validator-failed episode in both arms ended with the agent claiming DONE. The only task that failed at all was the silent-validation "
            "trap (`settings_strict`): in the receipt-on arm the agent clicked Save three times, received `no_op` each time, and still wrote "
            "*\"Although the 'Save' button click did not produce an immediate visible change … the task is complete\"*. "
            "The receipt was delivered, read, and overridden — the agreement-bias shape from A14, one layer down. "
            "Two caveats bound how much that null can carry: (1) the denominator is tiny — the agent solves 95-97% of these tasks in both arms, "
            "so P(DONE | fail) rests on 2-3 episodes per arm and its interval spans [34%, 100%]; (2) with temperature 0 and a fixed seed the "
            "three runs per task are near-identical trajectories (the per-run spread in `results/agent_loop.md` is a determinism check, not sampling variance). "
            "What the receipt *did* change is visible in the per-task table: the receipt-on arm needed fewer steps on the covered-button trap "
            "(the hint names the banner) and was the only arm to ever pass the silent-validation trap (once, by running out of steps after trying alternatives). "
            "A follow-up that can actually resolve the question needs a harder task set or a weaker agent so that failures are common, and a second seed."
        )
        A("")
    if se:
        pp = se["summary"]["per_policy"]
        rows = [
            [
                p,
                f"{100 * d['stale'] / d['n']:.1f}% ({d['stale']}/{d['n']})",
                f"{d['mean_wait_ms']:.0f}" if d["mean_wait_ms"] is not None else "-",
            ]
            for p, d in pp.items()
        ]
        A(
            "**Bench 2 (settlement vs fixed sleeps, `results/settlement.md`)** — stale rate of the post-action capture × time spent waiting, pooled over four effect mechanisms × eight delays (0-3000 ms), 20 trials per cell:"
        )
        A("")
        A(md_table(["policy", "stale (missed the effect)", "mean wait ms"], rows))
        A("")
        # per-mode receipt numbers
        cells = se["summary"]["cells"]

        def rate(mode, policy):
            cs = [c for c in cells if c["mode"] == mode and c["policy"] == policy]
            s = sum(c["stale"] for c in cs)
            n = sum(c["n"] for c in cs)
            return s, n

        r_fetch = rate("fetch", "receipt")
        r_tr = rate("transition", "receipt")
        r_two = rate("twostage", "receipt")
        r_to = rate("timeout", "receipt")
        r_to5 = rate("timeout", "receipt_q500")
        b05_fetch = rate("fetch", "blind_0.5")
        b20_fetch = rate("fetch", "blind_2.0")
        stale_modes = []
        for mode, r in (("fetch", r_fetch), ("transition", r_tr), ("two-stage", r_two)):
            stale_modes.append(f"{mode} {r[0]}/{r[1]}")
        A(
            f"The pooled stale rate depends on the (arbitrary, uniform) delay grid, so read the per-mode rows. Network-bound and CSS-transition effects: the receipt captured the landed "
            f"state in every trial at every delay up to 3 s (stale: {stale_modes[0]}, {stale_modes[1]}), waiting only as long as the effect took, while the 0.5 s sleep was stale on fetch in "
            f"{b05_fetch[0]}/{b05_fetch[1]} trials and the 2.0 s sleep in {b20_fetch[0]}/{b20_fetch[1]} (every effect slower than the constant). "
            f"Two-stage (fetch, then a loading spinner, then the render): **{stale_modes[2]} stale on this library state** — the first-pass run on an earlier state was 0/160; "
            f"the final `settle.py` ignores infinite animations, which fixed the perpetual-spinner page but also drops the transient spinner the action itself started "
            f"(`bench/FINDINGS.md` F8, with the fix that keeps both). The receipt still reports it honestly as `changed … settled_by=dom` — the spinner *is* a change — but the "
            f"capture is of the loading state, not the result. Bare `setTimeout` with nothing else keeping the page busy: {r_to[0]}/{r_to[1]} stale at quiet_ms=100 "
            f"(everything ≥ 250 ms), {r_to5[0]}/{r_to5[1]} at quiet_ms=500 (everything ≥ 500 ms) — the documented limitation, now with its curve; "
            f"the receipt reports it as `no_op … settled_by=quiet_window`, i.e. it states the bound it observed rather than claiming the effect landed."
        )
        A("")
    if ac and acp:
        s1, s2 = ac["summary"], acp["summary"]
        A(
            f"**Bench 3 (verdict accuracy, `results/accuracy.md` / `results/accuracy_prescroll.md`)** — 79 labelled cases × 3 trials: "
            f"**{100 * s1['accuracy']:.1f}%** with targets wherever they are on the page ({100 * s1['hard_accuracy']:.1f}% on the 20 tagged hard cases), "
            f"**{100 * s2['accuracy']:.1f}%** with targets pre-scrolled into view ({100 * s2['hard_accuracy']:.1f}% hard); 0 cases flaky across trials in either. "
            f"Misses: {len(s1['misses'])} / {len(s2['misses'])} cases, listed in the bench sections below."
        )
        A("")
    if ov:
        cells = ov["summary"]["cells"]

        def cell(page_sub, action, arm):
            for c in cells:
                if page_sub in c["page"] and c["action"] == action and c["arm"] == arm:
                    return c
            return {}

        fx = cell("buttons", "click", "receipt")
        fr = cell("buttons", "click", "raw")
        fn = cell("buttons", "click", "receipt_noshot")
        wk = cell("wikipedia", "click", "receipt")
        gh = cell("github", "click", "receipt")
        A(
            f"**Bench 1 (overhead, `results/overhead.md`)** — a click on the fixture page: raw Playwright p50/p90 {fr.get('p50_ms')}/{fr.get('p90_ms')} ms, "
            f"receipt {fx.get('p50_ms')}/{fx.get('p90_ms')} ms (no-screenshot variant {fn.get('p50_ms')}/{fn.get('p90_ms')} ms); "
            f"on the saved Wikipedia page ({next(c for c in cells if 'wikipedia' in c['page'])['elements']} elements) {wk.get('p50_ms')}/{wk.get('p90_ms')} ms and on the GitHub repo page "
            f"({next(c for c in cells if 'github' in c['page'])['elements']} elements) {gh.get('p50_ms')}/{gh.get('p90_ms')} ms. "
            f"The stage table shows where it goes: the ~100 ms quiet window is the floor, the two captures scale with the DOM "
            f"(≈{fx.get('capture_before_p50')} ms each on the fixture, ≈{gh.get('capture_before_p50')} ms each on GitHub), diff+verdict is "
            f"{min(c['diff_p50'] for c in cells if 'diff_p50' in c)}-{max(c['diff_p50'] for c in cells if 'diff_p50' in c)} ms across all cells."
        )
        A("")
    # ------------------------------------------------------------------ commands
    A("## Exact commands")
    A("")
    A("```bash")
    A("cd /home/admin/projects/action-receipt && PY=~/.venvs/action-receipt/bin/python")
    A(
        "$PY -m bench.fetch_fixtures                       # once: saves the 3 real pages under bench/fixtures/real/"
    )
    A("$PY -m bench.overhead   --n 50 --warmup 3")
    A("$PY -m bench.settlement --trials 20               # delays 0,50,100,250,500,1000,2000,3000")
    A("$PY -m bench.accuracy   --repeats 3")
    A("$PY -m bench.accuracy   --repeats 3 --prescroll")
    A(
        "$PY -m bench.agent_loop --runs 3 --max-steps 8 --seed 20260902 --max-calls 900   # qwen3.6:35b-a3b on LXC 102, reasoning_effort=none"
    )
    A(
        "$PY -m bench.tasks.selftest                                                    # every hard task: scripted solution passes, naive path fails"
    )
    A(
        "$PY -m bench.agent_loop_v2 --models qwen3.6:35b-a3b --set hard --seeds 20260902,20260903 --max-steps 12 --temperature 0.3 --max-calls 1300"
    )
    A(
        "$PY -m bench.agent_loop_v2 --models qwen3.5:4b      --set hard --seeds 20260902,20260903 --max-steps 12 --temperature 0.3 --max-calls 1300   # the two models run concurrently"
    )
    A(
        "$PY -m bench.agent_loop_v2 --summarize-only                                    # merges both models' episode files into results/agent_loop_v2.*"
    )
    A("$PY -m bench.realsite   --live                     # opt-in, one pass over 5 live pages")
    A("$PY -m bench.report                               # this file")
    A("# or: bench/run_all.sh [--live]")
    A("```")
    A("")
    A(
        "`bench/agent_loop.py` was restarted twice during development after harness bugs (a flattened-args parse, an ambiguous selector format in the observation) that would have "
        "inflated MAX_STEPS in *both* arms; the result file is the clean run. One task (`settings_confirm`) was redefined after that run because its original form "
        "depended on a `<select>`, which the MCP surface cannot operate except by keyboard (FINDINGS F6); it was re-run alone with `--resume --tasks settings_confirm` and its "
        "superseded traces kept under `results/agent_loop_traces/superseded_select_task/`."
    )
    A("")
    # ------------------------------------------------------------------ environment
    A("## Environment")
    A("")
    env = (ag or ov or {}).get("env", {})
    rows = [
        [k, env.get(k)]
        for k in (
            "chromium",
            "playwright",
            "mcp",
            "python",
            "cpu",
            "cpu_count",
            "mem_gb",
            "kernel",
            "platform",
            "git_head",
        )
        if k in env
    ]
    rows.append(
        [
            "agent model",
            f"{(ag or {}).get('env', {}).get('model')} via {(ag or {}).get('env', {}).get('model_endpoint')} (Ollama 0.20.5 on LXC 102, read-only; `reasoning_effort: none`, temperature 0, seed 20260902)",
        ]
    )
    rows.append(
        [
            "fixture server",
            "local `http.server` on 127.0.0.1 (bench/_common.py); every non-local request aborted in benches 1-4",
        ]
    )
    rows.append(
        [
            "viewports",
            "overhead 1280×800; settlement 1000×700; accuracy 1000×700; agent loop 1280×800 (server default); realsite 1280×800",
        ]
    )
    A(md_table(["item", "value"], rows))
    A("")
    # ------------------------------------------------------------------ per-bench sections
    A("## Bench 1 — overhead")
    A("")
    A(_section("overhead"))
    A("")
    A("## Bench 2 — settlement vs fixed sleeps")
    A("")
    A(_section("settlement"))
    A("")
    A("## Bench 3 — verdict accuracy")
    A("")
    A("### Targets wherever they are on the page (`accuracy.md`)")
    A("")
    A(_section("accuracy", heading_level=4))
    A("")
    A("### Targets pre-scrolled into view (`accuracy_prescroll.md`)")
    A("")
    A(_section("accuracy_prescroll", heading_level=4))
    A("")
    A("The full per-case tables (79 rows each) are in the two result files.")
    A("")
    A("## Bench 4 — agent-in-the-loop false completion")
    A("")
    A(_section("agent_loop"))
    A("")
    A(
        "Design notes. Both arms drive the **same** MCP server (`python -m action_receipt.server --cdp …`, one process per episode) against one Chromium; the harness "
        "observes and validates through a second CDP client. The observation shown to the model is a harness-side element listing (kind, CSS selector, label, value/state) plus "
        "URL, title, tabs and window scroll position — the same in both arms, and the previous *and* current observation are kept in full so a receipt-off agent can diff them itself. "
        "The only difference between arms is whether the tool result carries the receipt summary (`bench/prompts/receipt_on.txt` vs `receipt_off.txt`). "
        "Because both arms go through the receipt server, both get *measured settlement* before the observation; bench 4 therefore measures the value of the verdict/hint "
        "information, not of settlement (bench 2 measures that). Validators read `window.__state()` on every open tab."
    )
    A("")
    A("## Bench 4 v2 — harder tasks, three arms, two models")
    A("")
    A(_section("agent_loop_v2"))
    A("")
    A(
        "Design notes. Same agent, observation format, MCP path and validator mechanism as v1; differences: the 36-task hard set (`bench/tasks/`, documented in `bench/tasks/README.md`, "
        "self-tested by `bench.tasks.selftest`), a `select` tool (the MCP server gained one after FINDINGS F6), live-status text (`role=status`) in the observation, temperature 0.3 with "
        "two seeds (a fixed Ollama seed makes a repeat run a replay, so runs are indexed by seed), step cap 12, and the third arm. The `receipt_enforced` policy is `bench/agent_loop_v2.py::policy_reason`: "
        "deterministic, no model, keyed only on the receipt verdict history of the episode; a refusal returns the last hint as the tool RESULT and the episode continues; after two refusals the next `done` is accepted "
        "(`accepted_after_cap`). The validator is also read at every refusal so each one is classed justified/spurious. Each model runs in its own process with its own Chromium and episode file; "
        "`--summarize-only` merges them."
    )
    A("")
    A("## Bench 5 — real-site smoke (live, one pass)")
    A("")
    A(_section("realsite"))
    A("")
    A(
        "Notes: the GitHub page never settles (`never_settled: still busy ['animations']` at the 10 s cap) because it carries a perpetual CSS animation; the verdict is still `changed` from the scroll. "
        "The MDN breadcrumb click is `blocked` (`target_not_visible`) — the selector matched a hidden duplicate link first. The Wikipedia `type` receipt shows `window_scrolled dy=-800` next to `value_changed` — Playwright scrolled the search box back into view before typing (FINDINGS F1/F7 territory)."
    )
    A("")
    OUT.write_text("\n".join(L).rstrip() + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
